{"name": "test_2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "login = None\n\n    def test_2(login):\n        print(\"测试用例222\")\n>       assert 1==2\nE       assert 1 == 2\n\ncase\\ke18\\test_b.py:13: AssertionError"}, "attachments": [{"name": "stdout", "source": "5a6284be-5665-44bd-9417-a8c8369c97c6-attachment.txt", "type": "text/plain"}], "start": 1584173473748, "stop": 1584173473751, "uuid": "44532550-9b29-454f-bae9-e086a24cc38e", "historyId": "8a39c29bddda14f78287e64333f2bac4", "testCaseId": "3a359085bec913a747476f40a17ef89e", "fullName": "case.ke18.test_b#test_2", "labels": [{"name": "parentSuite", "value": "case.ke18"}, {"name": "suite", "value": "test_b"}, {"name": "host", "value": "5I1IP5FFPD06IKH"}, {"name": "thread", "value": "102000-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.ke18.test_b"}]}